### ISSUE TITLE
Can't find BICsuite.jar

### ISSUE THREAD

**Issue by Kevindroid** [schedulix/schedulix#10]
Hey Guys!

      I'm installing the schedulix on centos7. When I execute the "make new", the error message showed 

java.io.FileNotFoundException: /home/schedulix/schedulix-2.6.1/lib/BICsuite.jar (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at sun.tools.jar.Main.run(Main.java:195)
	at sun.tools.jar.Main.main(Main.java:1288)
java.io.FileNotFoundException: /home/schedulix/schedulix-2.6.1/lib/BICsuite.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.tools.jar.Main.getJarPath(Main.java:1163)
	at sun.tools.jar.Main.genIndex(Main.java:1195)
	at sun.tools.jar.Main.run(Main.java:317)
	at sun.tools.jar.Main.main(Main.java:1288)
chmod: cannot access ‘/home/schedulix/schedulix-2.6.1/lib/BICsuite.jar’: No such file or directory

     I do get into the lib and just find two files like centos7.spec /functions.sh .
     Did I miss anything? I followed the installation_en in doc. Please tell me how to solve it, thank you so much~ Have a good day!

**Comment by schedulix** [comment]
Hi Kevindroid,

what do the directory permissions look like and what user is used to compile? (the first "permission denied" leads me to this question).

Regards,

Ronald

**Comment by Kevindroid** [comment]
LOL~ I changed the permission of lib and make again then it succeeded. Thank you for your help,I should pay more attention on logs.
   Have a good day!
