### ISSUE TITLE
Version 2.6 install

### ISSUE THREAD

**Issue by seyhbold** [schedulix/schedulix#6]
Hi,

I am trying again to get version 2.6 running.
The build seemed to run fine. But when I try to start the server I get:

```
INFO    [main]          04 Feb 2015 09:57:22 GMT Starting Renew Ticket Thread
Exception in thread "main" java.lang.NoClassDefFoundError: de/independit/scheduler/server/repository/TableLoader
        at de.independit.scheduler.server.repository.SDMSRepository.loadTables(SDMSRepository.java:274)
        at de.independit.scheduler.server.repository.SDMSRepository.<init>(SDMSRepository.java:59)
        at de.independit.scheduler.server.Server.createRepository(Server.java:115)
        at de.independit.scheduler.server.Server.serverMain(Server.java:359)
        at de.independit.scheduler.BICServer.main(BICServer.java:144)
Caused by: java.lang.ClassNotFoundException: de.independit.scheduler.server.repository.TableLoader
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 5 more
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT ***********************************************
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT **                                           **
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT ** U N G R A C E F U L   S H U T D O W N ! ! **
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT **                                           **
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT ***********************************************
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT Release repository lock from 1423043841925
INFO    [Shutdown]      04 Feb 2015 10:00:42 GMT Shutdown completed
[scrolllog] Waiting for child (2972) to terminate
[scrolllog] Child exited with state 143
[scrolllog] Try to restart child (child terminated with exit code <> 0)
```

And indeed there is no TableLoader class in BICSuite.jar

What am I doing wrong?

Thank you very much
Regards Ludwig

**Comment by schedulix** [comment]
Hi Ludwig,

I'm sorry, it's hard to tell what you are doing wrong. But the most common cause for such situations is half-built systems. This can occur if you try to 'make', run into an error, fix the error and do a 'make' again.
In such cases it is better to do a 'make new', which cleans up intermediate results that can confuse 'make' every now and then.

I just did a fresh clone of the 2.6 version and a compile. I won't provide the entire output, but at least the last few lines (and a test) look like this:

```
...
Manifest-Version: 1.1
Program-Version: 2.6
Level: OPEN
Build: 5674078c31d0e758b4c90594ba11dcbb27ce1e0c
Build-Date: 04.02.2015 11:24
Copyright: Copyright (c) 2002-2014 independIT Integrative Technologies GmbH
Company: independIT Integrative Technologies GmbH
[ronald@cheetah src]$ cd ../lib
[ronald@cheetah lib]$ ls -l
total 1968
-rw-------. 1 ronald ronald 2008942 Feb  4 11:24 BICsuite.jar
-rw-rw-r--. 1 ronald ronald    1878 Feb  4 11:23 functions.sh
[ronald@cheetah lib]$ jar tvf BICsuite.jar | grep TableLoad
  2997 Wed Feb 04 11:24:30 CET 2015 de/independit/scheduler/server/repository/TableLoader.class
```
I hope this give you a clue, but don't hesitate to ask if not.

Regards,

Ronald

**Comment by seyhbold** [comment]
You were right. I started with a fresh Virtual Machine and now it worked.
I have no idea where I tool the wrong path.

Thank you very much
Regards
Ludwig
